### PR TITLE
Switch image processor from lwip to jimp

### PR DESCRIPTION
**Pull request by kodie**
Hi there! Great module, however I think that [Jimp](https://github.com/oliver-moran/jimp) would be a much better fit as an image processor than lwip.

First, in the readme you claim that asciify-image doesn't require any native dependencies, however it depends on lwip which [depends on](https://github.com/EyalAr/lwip#installation) [graphicsmagick](http://www.graphicsmagick.org/).
**Jimp is truly 100% Javascript**.

Second, [lwip has some issues with modern versions of Node](https://github.com/EyalAr/lwip/issues/297) which means that the current version of asciify-image can only be installed on older versions of Node.
**Jimp runs on most (if not all) versions of Node**.

Luckily, the APIs for lwip and Jimp are **very** similar and it required very little changes to switch over, better yet, it didn't require any changes to the asciify-image API.

This all came to be from a [discussion](https://github.com/kodie/npm-gif/issues/3) a few of us were having on a project of mine where we were talking about implementing asciify-image into the project.

Let me know what you think. Thanks!

### CODE REVIEW

**Comment by ajay-gandhi** [comment]
Hey Kodie,

This sounds great, the more JavaScript the better. I'll merge this now and publish a new version as soon as I can. Thanks for making the change!

**Comment by kodie** [comment]
Awesome! Thanks!

**Comment by benwiley4000** [comment]
Awesome. @ajay-gandhi do you think you'll be able to republish soon? 😁

**Comment by kodie** [comment]
I would recommend waiting to publish until we figure #5 out. :)

**Comment by ajay-gandhi** [comment]
@benwiley4000 @kodie Published v0.1.0 to npm

**Comment by kodie** [comment]
@ajay-gandhi Yes!!! 👏

**Pull request merged**
